### ISSUE TITLE
UI 디자인 수정

### ISSUE THREAD

**Issue by solanian** [ProjectInTheClass/Wa-ha#66]
1. 뒤로가기, 저장, 임시재생 버튼 재배치 및 디자인 수정
2. 썸네일 뷰 슬라이더 및 여백 디자인 수정하기 (슬라이더 색은 임의로 수정했습니다)
3. 삭제버튼을 누르기 전의 두려움을 고려한 디자인 수정

**Comment by KimTaeHyeong17** [comment]
1. 프로젝트 만드는 모달 백그라운드 색 어둡게 하고 tap 하면 dismiss
2. activity indicator (로딩화면) 어두운 배경에도 잘보이게 백그라운드 영역 추가
